### PR TITLE
Fix installation issues due to outdated deps

### PR DESCRIPTION
**Pull request by nikvdp**
This fixes pip installation and the associated installation issues:

- https://github.com/PressLabs/gitfs/issues/273
- https://github.com/PressLabs/gitfs/issues/271
- https://github.com/PressLabs/gitfs/issues/268
- https://github.com/PressLabs/gitfs/issues/267

### CODE REVIEW

**Comment by vtemian** [comment]
Hi @nikvdp,

Thanks for this pull request and for your time.
Can you pin the specific deps?

There can be cases in which a new version of `pygit` is released that will break `gitfs`.
Because of that, pined version of deps need to be specified and tested.

Thanks again!

**Comment by nikvdp** [comment]
Sure. I've updated requirements.txt and pinned  `pygit==0.26.0`. I think there may be a larger issue though, I've now tested this with `pygit==0.26.0`, `pygit==0.23.3`, and `pygit==0.24.1` (I manually rebuilt the corresponding libgit2 in each case since pip does not seem to be able to reliably build it). 

In each case the behavior was the same, I am able to mount a repo (was using a local clone of this repo to test, but saw similar behavior on other repos), and then wrote a few files into the mount's `current` folder:

```
touch 1 
touch 2
touch 3 
touch 4 
touch 5
touch 6
rsync -a tests/ copy-test/
```

With each version combo I eventually got this error:
```
touch: cannot touch '6': Read-only file system
```
In some cases I was able to make it all the way to the `rsync` command, but was never able to successfully run that. Once that error appears for the first time, all future attempts at writes fail with the same message.  

I had originally assumed this was an issue with incompatible libgit2 versions, but after seeing the same behavior across OSes and and libgit2 versions (incl. 0.23.3 and 0.24.1, both of which seem to have been [pinned before](https://github.com/PressLabs/gitfs/commit/48f0365717d01171fc406160fc0e73e22885dd23#diff-b4ef698db8ca845e5845c4618278f29aL2) I am starting to believe this is a separate issue. 

Any ideas? Should I open a separate issue for this, or is this likely to relate to the version of the underlying pygit2/libgit2?

**Comment by vtemian** [comment]
Awesome!

I guess that we can work on this PR and solve the issue.

Do you have some log output?
I suggest to mount it with debug option `-o log=/tmp/gitfs-debug.log,debug=true` and let's see what's the problem.

**Comment by sixtyfive** [comment]
Ouch. Project dead?

**Comment by vtemian** [comment]
Is going to be fixed in https://github.com/presslabs/gitfs/pull/309

**Pull request closed without merging**
